---
- name: Ubuntu Update Playbook
  hosts: all
  become: true
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes

    - name: Remove unused packages
      apt:
        autoremove: yes

    - name: Clean up APT cache
      apt:
        autoclean: yes
